#!/usr/bin/env bash
# Populates docker/custio_overlay/ so Dockerfile.custio can use a single COPY
# (avoids Docker/BuildKit "max depth exceeded" from 100+ per-file COPY layers).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/docker/custio_overlay"
rm -rf "$DEST"
mkdir -p "$DEST"

# Paths are repo-relative; mirrored under DEST so COPY docker/custio_overlay/ ./ works with WORKDIR /app
FILES=(
  "app/javascript/dashboard/assets/scss/_next-colors.scss"
  "app/javascript/dashboard/routes/dashboard/Dashboard.vue"
  "app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue"
  "app/javascript/dashboard/routes/dashboard/settings/SettingsWrapper.vue"
  "app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue"
  "app/javascript/dashboard/components-next/sidebar/provider.js"
  "app/javascript/dashboard/components-next/sidebar/Sidebar.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarAccountSwitcher.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarGroup.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarGroupHeader.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarGroupLeaf.vue"
  "app/javascript/dashboard/components-next/sidebar/ChannelLeaf.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarGroupSeparator.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarProfileMenu.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarCollapsedPopover.vue"
  "app/javascript/dashboard/components-next/sidebar/SidebarSubGroup.vue"
  "app/javascript/dashboard/components/ChatList.vue"
  "app/javascript/dashboard/components/ChatListHeader.vue"
  "app/javascript/dashboard/components/SettingsSection.vue"
  "app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue"
  "app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue"
  "app/javascript/dashboard/components/widgets/conversation/MessagesView.vue"
  "app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue"
  "app/javascript/dashboard/components/table/Table.vue"
  "app/javascript/dashboard/components/table/Pagination.vue"
  "app/javascript/dashboard/routes/dashboard/settings/integrations/Index.vue"
  "app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationItem.vue"
  "app/javascript/dashboard/routes/dashboard/settings/integrations/integrations.routes.js"
  "app/javascript/dashboard/store/modules/integrations.js"
  "app/javascript/dashboard/routes/dashboard/captain/assistants/scenarios/Index.vue"
  "app/javascript/dashboard/routes/dashboard/captain/assistants/guardrails/Index.vue"
  "app/javascript/dashboard/routes/dashboard/captain/assistants/guidelines/Index.vue"
  "app/javascript/dashboard/assets/scss/_base.scss"
  "app/javascript/dashboard/components/ui/Tabs/TabsItem.vue"
  "app/javascript/dashboard/components/ui/Banner.vue"
  "app/javascript/dashboard/components/ui/Label.vue"
  "app/javascript/dashboard/components/ui/PreviewCard.vue"
  "app/javascript/dashboard/components/widgets/WootWriter/CopilotEditor.vue"
  "app/javascript/dashboard/components/widgets/LoadingState.vue"
  "app/javascript/dashboard/components/Snackbar.vue"
  "app/javascript/dashboard/components-next/banner/Banner.vue"
  "app/javascript/dashboard/components-next/button/Button.vue"
  "app/javascript/dashboard/components-next/checkbox/Checkbox.vue"
  "app/javascript/dashboard/components-next/combobox/ComboBox.vue"
  "app/javascript/dashboard/components-next/copilot/CopilotInput.vue"
  "app/javascript/dashboard/components-next/dialog/Dialog.vue"
  "app/javascript/dashboard/components-next/filter/inputs/MultiSelect.vue"
  "app/javascript/dashboard/components-next/filter/inputs/SingleSelect.vue"
  "app/javascript/dashboard/components-next/filter/ConversationFilter.vue"
  "app/javascript/dashboard/components-next/HelpCenter/EmptyState/Portal/PortalEmptyState.vue"
  "app/javascript/dashboard/components-next/HelpCenter/LocaleCard/LocaleCard.vue"
  "app/javascript/dashboard/components-next/HelpCenter/Pages/LocalePage/AddLocaleDialog.vue"
  "app/javascript/dashboard/components-next/HelpCenter/Pages/LocalePage/LocaleList.vue"
  "app/javascript/dashboard/components-next/input/ChoiceToggle.vue"
  "app/javascript/dashboard/components-next/input/Input.vue"
  "app/javascript/dashboard/components-next/label/Label.vue"
  "app/javascript/dashboard/components-next/message/MessageMeta.vue"
  "app/javascript/dashboard/components-next/radioCard/RadioCard.vue"
  "app/javascript/dashboard/components-next/select/Select.vue"
  "app/javascript/dashboard/components-next/Settings/SettingsToggleSection.vue"
  "app/javascript/dashboard/components-next/switch/Switch.vue"
  "app/javascript/dashboard/components-next/tabbar/TabBar.vue"
  "app/javascript/dashboard/components-next/table/BaseTable.vue"
  "app/javascript/dashboard/components-next/table/BaseTableCell.vue"
  "app/javascript/dashboard/components-next/HelpCenter/HelpCenterLayout.vue"
  "app/javascript/dashboard/components-next/Campaigns/CampaignLayout.vue"
  "app/javascript/dashboard/components-next/captain/PageLayout.vue"
  "app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactHeader.vue"
  "app/javascript/dashboard/components-next/textarea/TextArea.vue"
  "app/javascript/dashboard/routes/dashboard/helpcenter/pages/PortalsLocalesIndexPage.vue"
  "app/javascript/dashboard/routes/dashboard/helpcenter/pages/PortalsIndexPage.vue"
  "app/javascript/dashboard/routes/dashboard/settings/inbox/components/AccountHealth.vue"
  "app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue"
  "app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/heatmaps/BaseHeatmap.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/heatmaps/BaseHeatmapContainer.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/MetricCard.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/OverviewReportFilters.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportHeader.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/StatsLiveReportsContainer.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/SummaryReports.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue"
  "app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue"
  "app/javascript/dashboard/routes/dashboard/inbox/InboxEmptyState.vue"
  "app/javascript/dashboard/routes/dashboard/inbox/components/InboxDisplayMenu.vue"
  "app/javascript/dashboard/routes/dashboard/contacts/pages/ContactsIndex.vue"
  "app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue"
  "app/javascript/dashboard/components-next/Contacts/ContactsListLayout.vue"
  "app/javascript/dashboard/components-next/Contacts/ContactsDetailsLayout.vue"
  "app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportsWrapper.vue"
  "app/javascript/dashboard/routes/dashboard/campaigns/pages/CampaignsPageRouteView.vue"
  "app/javascript/dashboard/routes/dashboard/settings/components/BaseSettingsHeader.vue"
  "app/javascript/dashboard/routes/dashboard/settings/account/Index.vue"
  "app/javascript/shared/helpers/timeHelper.js"
  "app/javascript/dashboard/App.vue"
  "app/javascript/dashboard/routes/dashboard/settings/profile/UserLanguageSelect.vue"
  "app/javascript/dashboard/i18n/locale/en/conversation.json"
  "app/javascript/dashboard/i18n/locale/sv/conversation.json"
  "app/javascript/dashboard/i18n/locale/en/contact.json"
  "app/javascript/dashboard/i18n/locale/sv/contact.json"
  "app/javascript/dashboard/i18n/locale/en/settings.json"
  "app/javascript/dashboard/i18n/locale/en/integrations.json"
  "app/javascript/dashboard/i18n/locale/en/helpCenter.json"
  "app/javascript/dashboard/i18n/locale/sv/settings.json"
  "app/javascript/dashboard/i18n/locale/sv/chatlist.json"
  "app/javascript/dashboard/i18n/locale/sv/components.json"
  "app/javascript/dashboard/i18n/locale/sv/general.json"
  "app/javascript/dashboard/i18n/locale/sv/agentMgmt.json"
  "app/javascript/dashboard/i18n/locale/sv/integrationApps.json"
  "app/javascript/dashboard/i18n/locale/sv/labelsMgmt.json"
  "app/javascript/dashboard/i18n/locale/sv/report.json"
  "app/javascript/dashboard/i18n/locale/sv/campaign.json"
  "app/javascript/dashboard/i18n/locale/sv/cannedMgmt.json"
  "app/javascript/dashboard/i18n/locale/sv/integrations.json"
  "app/javascript/dashboard/i18n/locale/sv/inbox.json"
  "app/javascript/dashboard/i18n/locale/sv/advancedFilters.json"
  "app/javascript/dashboard/i18n/locale/sv/auditLogs.json"
  "app/javascript/dashboard/i18n/locale/sv/automation.json"
  "app/javascript/dashboard/i18n/locale/sv/teamsSettings.json"
  "app/javascript/dashboard/i18n/locale/sv/helpCenter.json"
  "app/javascript/dashboard/i18n/locale/sv/bulkActions.json"
  "app/javascript/dashboard/i18n/locale/sv/datePicker.json"
  "app/javascript/dashboard/i18n/locale/sv/companies.json"
  "app/javascript/dashboard/i18n/locale/sv/inboxMgmt.json"
  "app/javascript/portal/application.scss"
  "app/javascript/portal/portalThemeHelper.js"
  "app/javascript/portal/components/PublicArticleSearch.vue"
  "app/javascript/portal/components/PublicSearchInput.vue"
  "app/javascript/portal/components/SearchSuggestions.vue"
  "app/javascript/portal/portalHelpers.js"
)

missing=0
for rel in "${FILES[@]}"; do
  src="$ROOT/$rel"
  if [[ ! -f "$src" ]]; then
    echo "ERROR: missing source file: $rel" >&2
    missing=1
    continue
  fi
  target="$DEST/$rel"
  mkdir -p "$(dirname "$target")"
  cp "$src" "$target"
done
if [[ "$missing" -ne 0 ]]; then
  exit 1
fi
echo "Prepared $DEST (${#FILES[@]} files)."
